version: '3.8'

services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kickoff
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db  
  
  app:
    build: .
    image: saidatoui/backendexpress:1
    restart: always
    container_name: backendexpress
    ports:
      - '3000:3000'
    depends_on:
      - db
  
volumes:
  mongo-data:
