# Use official Node.js image as the base image
FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

RUN npm rebuild bcrypt --build-from-source

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose port 3000 (change this if your app listens on a different port)
EXPOSE 3000

RUN npm install -g nodemon

# Command to run the application
CMD ["nodemon", "server.js"]
